# Generated by Django 2.0 on 2018-05-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_org_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='org_name',
            new_name='course_org',
        ),
    ]
