# Generated by Django 2.0 on 2018-04-14 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydict',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 14, 14, 55, 56, 526170)),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 14, 14, 55, 56, 526170)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 14, 14, 55, 56, 527172)),
        ),
    ]
