# Generated by Django 2.0 on 2018-05-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizition', '0006_courseorg_course_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='org/teacher/%Y/%m', verbose_name='机构封面'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='org/course/%Y/%m', verbose_name='机构封面'),
        ),
    ]
